import json
from pathlib import Path

from app.provenance.evidence import create_evidence


OGA_OUTPUT_DIR = (
    Path(__file__).resolve().parents[2]
    / "data"
    / "oga_output"
)

def load_oga_output(file_name: str) -> dict:
    """
    Load a JSON output generated by OGA Budget Lens.

    The OGA repository is read-only from this project.
    """
    file_path = OGA_OUTPUT_DIR / file_name

    if not file_path.exists():
        raise FileNotFoundError(
            f"OGA output file not found: {file_path}"
        )

    with file_path.open("r", encoding="utf-8") as file:
        return json.load(file)


def get_oga_source_info() -> dict:
    """
    Returns provenance information about OGA Budget Lens.
    """
    return create_evidence(
        source_name="OpenGov Africa - OGA Budget Lens",
        source_url="https://github.com/OpenGovAfrica/oga-budget-lens",
        claim=(
            "OGA Budget Lens is used as a read-only source "
            "of extracted budget data."
        ),
        evidence="Provenance-first",
        source_type="repository",
    )


def search_oga_evidence(data: dict, query: str) -> list:
    """
    Search one OGA JSON document and return relevant evidence.

    The search is deterministic and does not use an LLM.

    Evidence is grouped by contiguous matching rows to avoid
    returning duplicated overlapping results.
    """

    results = []

    query = query.lower().strip()

    if not query:
        return results

    query_terms = [
        term
        for term in query.split()
        if len(term) >= 3
    ]

    if not query_terms:
        return results

    total_terms = len(query_terms)

    for page in data.get("tables", []):
        page_number = page.get("page_number")

        for table in page.get("tables", []):
            rows = table.get("rows", [])

            matching_indexes = []

            for index, row in enumerate(rows):
                text = " ".join(
                    str(cell)
                    for cell in row
                    if cell is not None
                ).strip()

                if not text:
                    continue

                text_lower = text.lower()

                matching_terms = [
                    term
                    for term in query_terms
                    if term in text_lower
                ]

                if not matching_terms:
                    continue

                matched_count = len(matching_terms)
                match_score = matched_count / total_terms
                exact_phrase_match = query in text_lower

                if exact_phrase_match or matched_count == total_terms:
                    match_strength = "STRONG"
                elif match_score >= 0.5:
                    match_strength = "PARTIAL"
                else:
                    match_strength = "WEAK"

                if match_strength != "WEAK":
                    matching_indexes.append(
                        {
                            "index": index,
                            "text": text,
                            "matching_terms": matching_terms,
                            "matched_count": matched_count,
                            "match_score": match_score,
                            "match_strength": match_strength,
                            "exact_phrase_match": exact_phrase_match,
                        }
                    )

            processed_indexes = set()

            for match in matching_indexes:
                index = match["index"]

                if index in processed_indexes:
                    continue

                processed_indexes.add(index)

                context_parts = []

                # Previous row
                if index > 0:
                    previous_row = " ".join(
                        str(cell)
                        for cell in rows[index - 1]
                        if cell is not None
                    ).strip()

                    if previous_row:
                        context_parts.append(
                            f"Previous row: {previous_row}"
                        )

                # Matching row
                context_parts.append(
                    f"Matching row: {match['text']}"
                )

                # Next row
                if index + 1 < len(rows):
                    next_row = " ".join(
                        str(cell)
                        for cell in rows[index + 1]
                        if cell is not None
                    ).strip()

                    if next_row:
                        context_parts.append(
                            f"Next row: {next_row}"
                        )

                contextual_evidence = "\n".join(
                    context_parts
                )

                evidence = create_evidence(
                    source_name=(
                        "OpenGov Africa - OGA Budget Lens"
                    ),
                    source_url=(
                        "https://github.com/OpenGovAfrica/"
                        "oga-budget-lens"
                    ),
                    claim=f"Evidence related to: {query}",
                    evidence=contextual_evidence,
                    source_type="oga_output",
                )

                evidence["page_number"] = page_number
                evidence["matching_terms"] = (
                    match["matching_terms"]
                )
                evidence["matched_count"] = (
                    match["matched_count"]
                )
                evidence["total_query_terms"] = total_terms
                evidence["match_score"] = round(
                    match["match_score"],
                    2,
                )
                evidence["match_strength"] = (
                    match["match_strength"]
                )
                evidence["exact_phrase_match"] = (
                    match["exact_phrase_match"]
                )

                results.append(evidence)

    results.sort(
        key=lambda item: (
            item["exact_phrase_match"],
            item["match_score"],
            item["matched_count"],
        ),
        reverse=True,
    )

    unique_results = []
    seen = set()

    for result in results:
        key = (
            result.get("source_file"),
            result.get("page_number"),
            result.get("evidence", "").strip(),
        )

        if key not in seen:
            seen.add(key)
            unique_results.append(result)

    return unique_results[:5]


def search_all_oga_evidence(query: str) -> list:
    """
    Search all JSON outputs generated by OGA Budget Lens.
    """

    results = []

    for file_path in OGA_OUTPUT_DIR.glob("*.json"):
        try:
            data = load_oga_output(file_path.name)

            matches = search_oga_evidence(
                data,
                query,
            )

            for match in matches:
                match["source_file"] = file_path.name
                results.append(match)

        except Exception as exc:
            results.append(
                {
                    "source_file": file_path.name,
                    "error": str(exc),
                }
            )

    results.sort(
        key=lambda item: (
            item.get("exact_phrase_match", False),
            item.get("match_score", 0),
        ),
        reverse=True,
    )

    unique_results = []
    seen = set()

    for result in results:
        key = (
            result.get("source_file"),
            result.get("page_number"),
            result.get("evidence", "").strip(),
        )

        if key not in seen:
            seen.add(key)
            unique_results.append(result)

    return unique_results[:5]


def search_oga(query: str) -> list:
    """
    Agent-facing search tool for OGA evidence.
    """

    return search_all_oga_evidence(query)
